<a href="https://colab.research.google.com/github/iamjaco/Text_Generation/blob/main/Paragraph_Auto_Generator_Hugging_Face_GPT2_%26_Transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

!pip install transformers #install the library

     |████████████████████████████████| 2.5MB 9.5MB/s 
     |████████████████████████████████| 901kB 37.8MB/s 
     |████████████████████████████████| 3.3MB 33.2MB/s 


In [ ]:
import tensorflow as tf
from transformers import GPT2LMHeadModel, GPT2Tokenizer #importing the main model and tokenizer

In [ ]:
tokenizer = GPT2Tokenizer.from_pretrained("gpt2-large")

In [ ]:
model = GPT2LMHeadModel.from_pretrained("gpt2-large", pad_token_id=tokenizer.eos_token_id)

In [ ]:
sentence = 'You will always succeed in Life' #input sentence

In [ ]:
input_ids = tokenizer.encode(sentence, return_tensors='pt')

In [ ]:
input_ids # checking the tesors returned

tensor([[1639,  481, 1464, 6758,  287, 5155]])

In [ ]:
output = model.generate(input_ids, max_length=50, num_beams=5, no_repeat_ngram_size=2, early_stopping=True)

/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)


In [ ]:
print(tokenizer.decode(output[0], skip_special_tokens=True))#printing results

You will always succeed in Life, but you will never be successful in Death."

"I am not afraid of death, because I know that I am going to be with you when you die. I will be waiting for you, and I


In [ ]:
sentence = 'Artificial intelligence is the key'

In [ ]:
input_ids = tokenizer.encode(sentence, return_tensors='pt')

In [ ]:
input_ids

tensor([[8001, 9542, 4430,  318,  262, 1994]])

In [ ]:
output = model.generate(input_ids, max_length=500, num_beams=5, no_repeat_ngram_size=2, early_stopping=True) #setting length as 500 to generate larger output text

In [ ]:
output

tensor([[ 8001,  9542,  4430,   318,   262,  1994,   284, 39052,   262, 26045,
           286,   262,  6881,    11,   475,   340,   338,   635,   262,  2723,
           286,   257,  1256,   286,   674,  2761,    13,   198,   198,   818,
           257,   649,  3348,  3199,   287,   262,  3989,  5800,  8007,  1817,
            11,   257,  1074,   286,  4837,   422,   262,  2059,   286,  3442,
            11, 14727,    11,   290,   262,  2351,  5136,   286, 20130,   290,
          8987,   357,    45,  8808,     8,   287, 12822,  1555, 30359,    11,
         10769,    11,  8477,   257,   835,   284,  2251,   281, 11666,  4430,
           357, 20185,     8,  1080,   326,   460,  2193,   422,   663, 10135,
           290,  2987,   663,  2854,   625,   640,    13,   383,  1080,    11,
           543,   484,   869,   257,   366,   710,  1523,  3127,   553,   318,
          6007,   286,  4673,   284,  7564,  7572,   287,  4263,    11,  7564,
          5563,   287,   257,  2008,    11,   393,  

In [ ]:
print(tokenizer.decode(output[0], skip_special_tokens=True))

Artificial intelligence is the key to unlocking the mysteries of the universe, but it's also the source of a lot of our problems.

In a new paper published in the journal Science Advances, a team of researchers from the University of California, Berkeley, and the National Institute of Standards and Technology (NIST) in Gaithersburg, Maryland, describes a way to create an artificial intelligence (AI) system that can learn from its mistakes and improve its performance over time. The system, which they call a "neural network," is capable of learning to recognize patterns in images, recognize objects in a video, or even learn how to play a musical instrument. In the paper, the researchers describe how they created the neural network and how it can be used to train an AI system to perform a variety of tasks, such as recognizing objects and playing musical instruments.


Neural networks, also known as deep neural networks or deep learning, are a type of machine learning algorithm that is bas

In [ ]:
text = tokenizer.decode(output[0],skip_special_tokens = True)
with open('AIBLOG.txt','w') as f:
  f.write(text)